services:
  mongo:
    image: mongo:7
    container_name: raw-mongo
    restart: unless-stopped
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: rootpassword
      MONGO_INITDB_DATABASE: raw_scryfall
    command: ["mongod", "--wiredTigerCacheSizeGB", "1"]
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data: